# ===========
# AWS STORAGE
# ===========
# Persistent volume claim for URL Map (Redis)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-urlmap
  labels:
    app: bingo
    service: urlmap-service
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: 'sc-aws'
  resources:
    requests:
      storage: 10Gi
---
# Storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-aws
  labels:
    app: bingo
    service: urlmap-service
reclaimPolicy: Retain
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
  encrypted: "false"
