# ========
# Services
# ========
# indexing service
apiVersion: v1
kind: Service
metadata:
  name: indexing-service
spec:
  selector:
    service: indexing-service
  ports:
  - protocol: TCP
    port: 9090
    targetPort: inverted-index
---
# inverted-index-service
apiVersion: v1
kind: Service
metadata:
  name: inverted-index-service
spec:
  selector:
    service: inverted-index-service
  ports:
    - protocol: TCP
      port: 27017
      targetPort: inverted-index
---
# mongodb service
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: bingo
    service: inverted-index-service
spec:
  ports:
  - name: inverted-index
    port: 27017
  clusterIP: None
  selector:
    role: mongo
---
# ====
# Pods
# ====
# # Storage class [ AWS ]
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: sc-index
#   labels:
#     app: bingo
#     service: inverted-index-service
# reclaimPolicy: Retain
# volumeBindingMode: Immediate
# provisioner: kubernetes.io/aws-ebs
# allowVolumeExpansion: true
# parameters:
#   type: io1
#   iopsPerGB: "5"
#   fsType: ext4
#   encrypted: "false"
# ---
# Storage class [ local ]
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-index
  labels:
    app: bingo
    service: inverted-index-service
reclaimPolicy: Retain
volumeBindingMode: Immediate
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true
---
# inverted index (mongodb) statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  selector:
    matchLabels:
      app: bingo
      service: inverted-index-service
  replicas: 1
  template:
    metadata:
      labels:
        app: bingo
        service: inverted-index-service
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "sc-index"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
# ======================
# Deployments / replicas
# ======================

# INDEXER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer-pod
spec:
  selector:
    matchLabels:
      app: bingo
      service: indexing-service
  replicas: 2
  template:
    metadata:
      labels:
        app: bingo
        service: indexing-service
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: service
                  operator: NotIn
                  values:
                  - crawling-service
      containers:
      - name: indexer-container
        image: bingocrawler/indexer:latest
        args: ["$(ENV_FILE)"]
        env:
        - name: ENV_FILE
          valueFrom:
            secretKeyRef:
              name: deploy
              key: ENV_FILE
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY
