# ========
# SERVICES
# ========
# crawling service
apiVersion: v1
kind: Service
metadata:
  name: crawling-service
spec:
  selector:
    service: crawling-service
  ports:
    - name: crawling-port
      protocol: TCP
      port: 8080
      targetPort: 8080
# balancing service
apiVersion: v1
kind: Service
metadata:
  name: balancing-service
spec:
  selector:
    service: balancing-service
  ports:
    - name: balancing-port
      protocol: TCP
      port: 23456
      targetPort: 23456
---
# ====
# PODS
# ====
# URL Map (Redis) pod
apiVersion: v1
kind: Pod
metadata:
  name: urlmap-pod
  labels:
    app: bingo
    service: balancing-service
spec:
  volumes:
    - name: urlmap-storage
      persistentVolumeClaim:
        claimName: pvc-urlmap
    - name: redisconfig
      configMap:
        name: redisconfig
  containers:
  - name: urlmap
    image: redis:latest
    args:
      - /etc/redis/redis.conf
    volumeMounts:
    - name: urlmap-storage
      mountPath: /data
      subPath: urlmap
    - name: redisconfig
      mountPath: /etc/redis
    ports:
    - containerPort: 6379
      name: urlmap-port
      protocol: TCP
---
# domain balancer
apiVersion: v1
kind: Pod
metadata:
  name: domain-balancer-pod
  labels:
    app: bingo
    service: balancing-service
spec:
  containers:
  - name: domain-balancer
    image: bingocrawler/domain-balancer:latest
    ports:
      - name: balancer-port
        containerPort: 23456
        protocol: TCP
---
# =======
# STORAGE
# =======
# storage class for aws deploy
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-aws
  labels:
    app: bingo
    service: balancing-service
reclaimPolicy: Retain
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
  encrypted: "false"
---
# storage class for local deploy
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-local
  labels:
    app: bingo
    service: balancing-service
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-local
  local:
    path: /mnt/disks/vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
# persistent volume claim for URL Map (redis)
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-urlmap
  labels:
    app: bingo
    service: balancing-service
spec:
  accessModes: [ReadWriteOnce]
# CHANGE WHEN IN AWS:
  storageClassName: 'sc-local'
# storageClassName: 'sc-aws'
  resources:
    requests:
      storage: 10Gi
---
# ======================
# DEPLOYMENTS / REPLICAS
# ======================
# CRAWLER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-pod
spec:
  selector:
    matchLabels:
      app: bingo
      service: crawling-service
  replicas: 3
  template:
    metadata:
      labels:
        app: bingo
        service: crawling-service
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: In
                values:
                - crawling-service
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: In
                values:
                - crawling-service
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: crawler-container
        image: bingocrawler/crawler:latest
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY
