apiVersion: skaffold/v1
kind: Config
metadata:
  name: deploy
build:
  artifacts:
  # - image: bingocrawler/balancer
  #   context: ../balancer
  # - image: bingocrawler/crawler
  #   context: ../crawler
  - image: bingocrawler/indexer
    context: ../indexer
profiles:
  - name: aws
    activation:
      - kubeContext: aws
    deploy:
      kubectl:
        manifests:
        # - kubeconfig.storage.aws.yaml
        # - kubeconfig.crawling.yaml
        - kubeconfig.indexing.yaml
  - name: minikube
    activation:
      - kubeContext: minikube
    deploy:
      kubectl:
        manifests:
        # - kubeconfig.storage.minikube.yaml
        # - kubeconfig.crawling.yaml
        - kubeconfig.indexing.yaml
