# apiVersion: v1
# kind: Config
# preferences: {}
# current-context: ""
# clusters:
# - cluster:
#     certificate-authority: /home/lucas/.minikube/ca.crt
#     server: https://192.168.99.101:8443
#   name: bingo

# contexts:
# - context:
#     cluster: bingo
#     user: bingo
#   name: bingo

# users:
# - name: bingo
#   user:
#     client-certificate: /home/lucas/.minikube/client.crt
#     client-key: /home/lucas/.minikube/client.key

# ---
apiVersion: v1
kind: Service
metadata:
  name: crawler-service
spec:
  selector:
    app: bingo
  ports:
    - name: balancer
      protocol: TCP
      port: 9966
      targetPort: 9966

---
apiVersion: v1
kind: Service
metadata:
  name: indexer-service
spec:
  selector:
    app: bingo
  ports:
    - name: inverted-index
      protocol: TCP
      port: 9966
      targetPort: 9966

---
apiVersion: v1
kind: Pod
metadata:
  name: bingo-crawler-pod
#   namespace: bingo-crawler
spec:
  containers:
  - name: bingo-crawler
    image: bingocrawler/crawler:latest
#   imagePullSecrets:
#   - name: dockerhub-credential
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bingo-crawler-deploy
spec:
  selector:
    matchLabels:
      app: web-crawler
  replicas: 3
  template:
    metadata:
      labels:
        app: web-crawler
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web-crawler
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - crawler
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: bingo-crawler
        image: bingocrawler/crawler:latest
