# apiVersion: v1
# kind: Config
# preferences: {}
# current-context: ""
# clusters:
# - cluster:
#     certificate-authority: /home/lucas/.minikube/ca.crt
#     server: https://192.168.99.101:8443
#   name: bingo

# contexts:
# - context:
#     cluster: bingo
#     user: bingo
#   name: bingo

# users:
# - name: bingo
#   user:
#     client-certificate: /home/lucas/.minikube/client.crt
#     client-key: /home/lucas/.minikube/client.key

# ---

# ========
# Services
# ========
apiVersion: v1
kind: Service
metadata:
  name: crawler-service
spec:
  selector:
    service: indexing
  ports:
    - name: balancer
      protocol: TCP
      port: 9966
      targetPort: 9966
---
apiVersion: v1
kind: Service
metadata:
  name: indexer-service
spec:
  selector:
    service: crawling
  ports:
    - name: inverted-index
      protocol: TCP
      port: 9966
      targetPort: 9966

---

# ====
# Pods
# ====

apiVersion: v1
kind: Pod
metadata:
  name: url-map-pod
  labels:
    app: bingo
    service: crawling
spec:
  containers:
  - name: url-map
    image: bingocrawler/url-map:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: domain-balancer-pod
  labels:
    app: bingo
    service: crawling
spec:
  containers:
  - name: domain-balancer
    image: bingocrawler/domain-balancer:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: inverted-index-pod
  labels:
    app: bingo
    service: indexing
spec:
  containers:
  - name: inverted-index
    image: bingocrawler/inverted-index:latest

---

# ======================
# Deployments / replicas
# ======================

# CRAWLER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-pod
spec:
  selector:
    matchLabels:
      app: bingo
      service: crawling
  replicas: 3
  template:
    metadata:
      labels:
        app: bingo
        service: crawling
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: In
                values:
                - crawling
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: In
                values:
                - crawling
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: crawler-container
        image: bingocrawler/crawler:latest

---
# INDEXER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer-pod
spec:
  selector:
    matchLabels:
      app: bingo
      service: indexing
  replicas: 3
  template:
    metadata:
      labels:
        app: bingo
        service: indexing
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: In
                values:
                - indexing
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: In
                values:
                - indexing
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: indexer-container
        image: bingocrawler/indexer:latest
