apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority: /home/lucas/.minikube/ca.crt
    server: https://192.168.99.101:8443
  name: bingo
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1UQXdOekl4TlRNMU1sb1hEVEk1TVRBd05ESXhOVE0xTWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3pCCmlnTk91eGlnQnR2dmtGZXJjUXlaQkVFSFFrOVBNTW42ekpESkxjMUIzWHFRclpvcXNiY2k3bmVacXZZUlVjRmMKTEVZYUt2WUJhQnI1UTh2MnFRUVNuc3orZUwwNUEyNHh3QkdMdGZYU0srYzlFRmNRajFLMjhaUjBDVkFadEJqSQo4QUg5eTJlK1FlR0M4eDlEdG1nMnFZN29YZHZoeTRNOThpbFM1SkxBMXNCRDdCenhpTFREYlB6cDlQVzJRZDd5CkVYU3VUT0ozOWFZM3ZPZnMzQS9RaDFjZXRwUXFDU0RPRXpCekpMbDRGRm5pcmYzYVRIZ05wL3paWjJpc0JzU0MKUlM1V0R2WGZ0RXVuNWJlaSs1ajF1WnFRVGRVRVIzanphM2F3Y2RHMlZ6T3haRW5UYjlXYWpDa0R5dGVhOXdpRApYK052dUQ5M0NYRXdHT2M5Q01rQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFQ3o3RENWY0lIUlU5b1FnY2V1OG42WUhuVi8KbEhOekNuVHJNeWhxWEZuckJEL0gzYkN0UDFtVlBoV2ZiZ1RsSnBxVzZBaEc3RFJNNXlmZ2gzNDg0bDNYWitzYgpBT0JsenVHMFUyN01HUmZjR3VYeEFhcXd0MFByVzF0bWJ2cDdZZC9Sb1BSbVFoM3hzUW9EODJ1cFRkVit5dEEzCitaN21jcEZ0MXJySkx1aDdUWG42L1l0dHNjMkZ6bGYxKzlaQTZ6dHRaVXVuSDhZSGlnY3BkNE5LRlVGMEtkTUkKRGJmZW5WcEF5MTBHSXhJWklyT3Z0aHRhWlRQZkNndFBIeFRaNVRnUk8rQjh6ODFIWk1tS3A5V3VKRTMwWWE5eQo2cTZ2cExnRUpFZ3J3elIyWkh4MVJsQ1ErSUtFTFIyVVArM2dlZUdGQ3paR2x2c3J4QXRaMFZ6V1ZUOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://529251F1E4DE3C76E3C51BDB2549F838.yl4.us-east-2.eks.amazonaws.com
  name: bingo-nano-002.us-east-2.eksctl.io
- cluster:
    certificate-authority: /home/lucas/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube

contexts:
- context:
    cluster: bingo-nano-002.us-east-2.eksctl.io
    user: Peasant@bingo-nano-002.us-east-2.eksctl.io
  name: Peasant@bingo-nano-002.us-east-2.eksctl.io
- context:
    cluster: bingo
    user: bingo
  name: bingo
- context:
    cluster: minikube
    user: minikube
  name: minikube

current-context: Peasant@bingo-nano-002.us-east-2.eksctl.io

users:
- name: Peasant@bingo-nano-002.us-east-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - bingo-nano-002
      command: aws-iam-authenticator
      env: null
- name: bingo
  user:
    client-certificate: /home/lucas/.minikube/client.crt
    client-key: /home/lucas/.minikube/client.key
- name: minikube
  user:
    client-certificate: /home/lucas/.minikube/client.crt
    client-key: /home/lucas/.minikube/client.key
