{
 "title": "BINGO | Dashboard",
 "description": "BINGO Metrics",
 "tags": [ "bingo" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "node",
    "query": "label_values(node_cpu_seconds_total{mode=\"system\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu_seconds_total{mode=\"system\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory | Usage by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes) by (instance)",
     "legendFormat": "AVAIL | {{instance}}"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes) by (instance)",
     "legendFormat": "TOTAL | {{instance}}"
    }
   ]
  },
  {
   "title": "Indexed documents over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bingo_indexer_processed_files_total{kubernetes_namespace=~\"^$namespace$\"}) by (pod)",
     "legendFormat": "Indexed documents"
    },
    {
     "expr": "count(count(bingo_indexer_processed_files_total) by (kubernetes_pod_name))",
     "legendFormat": "Indexer pods"
    }
   ]
  },
  {
   "title": "Memory | Used by BINGO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"^$namespace$\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"^$namespace$\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Crawled documents over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bingo_crawler_requests_success_total{kubernetes_namespace=~\"^$namespace$\"}) by (pod)",
     "legendFormat": "Indexed documents"
    },
    {
     "expr": "count(count(bingo_crawler_requests_success_total) by (kubernetes_pod_name))",
     "legendFormat": "Crawler pods"
    }
   ]
  },
  {
   "title": "Network | Received bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"^$namespace$\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"^$namespace$\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(container_network_receive_bytes_total{namespace=~\"default\"}) by (instance)",
     "legendFormat": "Total {{instance}}"
    }
   ]
  },
  {
   "title": "Network | Transmit bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"^$namespace$\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"^$namespace$\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(container_network_transmit_bytes_total{namespace=~\"default\"}) by (instance)",
     "legendFormat": "Total {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 12 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_disk_written_bytes_total{instance=~\"$node:$port\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU | Usage by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(sum(irate(node_cpu_seconds_total{instance=~\"$node:$port\"}[30s])) by (instance,cpu) - sum(irate(node_cpu_seconds_total{instance=~\"$node:$port\", mode='idle'}[30s])) by (instance,cpu)) by (instance)",
     "legendFormat": "Utilization | {{instance}}"
    }
   ]
  },
  {
   "title": "CPU | Used by BINGO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 16 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_disk_read_bytes_total{instance=~\"$node:$port\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}